spring:
  application:
    name: BookifyAZ

  datasource:
    url: jdbc:postgresql://localhost:5432/bookifyaz_db
    username: bookifyaz
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    secret: bXMxNG1zMTRtczE0bXMxNG1zMTRtczE0bXMxNG1zMTRtczE0bXMxNG1zMTRtczE0bXMxNG1zMTRtczE0bXMxNA==
    token:
      expirationTime: 60

server:
  port: 8086

logging:
  level:
    com.bookifyaz.bookifyaz.tenant: INFO
    com.bookifyaz.bookifyaz.service: INFO

