CREATE TABLE tenants
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    slug       VARCHAR(255),
    logo_url   VARCHAR(255),
    timezone   VARCHAR(255),
    is_active  BOOLEAN                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tenants PRIMARY KEY (id)
);