CREATE TABLE users
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name     VARCHAR(255),
    email         VARCHAR(255),
    phone         VARCHAR(255),
    password_hash VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE authority
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(255),
    CONSTRAINT pk_authority PRIMARY KEY (id)
);

CREATE TABLE user_authorities
(
    authority_id BIGINT  NOT NULL,
    user_id      INTEGER NOT NULL,
    CONSTRAINT fk_user_authorities_authority FOREIGN KEY (authority_id) REFERENCES authority (id),
    CONSTRAINT fk_user_authorities_user FOREIGN KEY (user_id) REFERENCES users (id)
);