CREATE TABLE tenant_user
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   INTEGER,
    tenant_id INTEGER,
    CONSTRAINT pk_tenant_user PRIMARY KEY (id),
    CONSTRAINT fk_tenant_user_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_tenant_user_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);