CREATE TABLE staff
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bio       VARCHAR(255),
    photo_url VARCHAR(255),
    is_active BOOLEAN                                  NOT NULL,
    tenant_id INTEGER,
    user_id   INTEGER,
    CONSTRAINT pk_staff PRIMARY KEY (id),
    CONSTRAINT fk_staff_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_staff_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE services
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    min_duration INTEGER                                  NOT NULL,
    price        DECIMAL,
    color        VARCHAR(255),
    is_active    BOOLEAN                                  NOT NULL,
    tenant_id    INTEGER,
    CONSTRAINT pk_services PRIMARY KEY (id),
    CONSTRAINT fk_services_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE TABLE staff_service
(
    id         INTEGER NOT NULL,
    staff_id   INTEGER,
    service_id INTEGER,
    CONSTRAINT pk_staff_service PRIMARY KEY (id),
    CONSTRAINT fk_staff_service_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
    CONSTRAINT fk_staff_service_service FOREIGN KEY (service_id) REFERENCES services (id)
);