CREATE TABLE working_hours
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day_of_week INTEGER                                  NOT NULL,
    start_time  TIME WITHOUT TIME ZONE,
    end_time    TIME WITHOUT TIME ZONE,
    is_off      BOOLEAN                                  NOT NULL,
    staff_id    INTEGER,
    CONSTRAINT pk_working_hours PRIMARY KEY (id),
    CONSTRAINT fk_working_hours_staff FOREIGN KEY (staff_id) REFERENCES staff (id)
);

CREATE TABLE time_off
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date DATE,
    end_date   DATE,
    reason     VARCHAR(255),
    staff_id   INTEGER,
    CONSTRAINT pk_time_off PRIMARY KEY (id),
    CONSTRAINT fk_time_off_staff FOREIGN KEY (staff_id) REFERENCES staff (id)
);
