CREATE TABLE booking
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_at   TIMESTAMP WITHOUT TIME ZONE,
    end_at     TIMESTAMP WITHOUT TIME ZONE,
    status     VARCHAR(255),
    notes      VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    tenant_id  INTEGER,
    client_id  INTEGER,
    staff_id   INTEGER,
    service_id INTEGER,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_booking_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_booking_client FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT fk_booking_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
    CONSTRAINT fk_booking_service FOREIGN KEY (service_id) REFERENCES services (id)
);
CREATE TABLE booking_status_history
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_status VARCHAR(255),
    to_status   VARCHAR(255),
    changed_at  TIMESTAMP WITHOUT TIME ZONE,
    booking_id  INTEGER,
    changed_by  INTEGER,
    CONSTRAINT pk_booking_status_history PRIMARY KEY (id),
    CONSTRAINT fk_bsh_booking FOREIGN KEY (booking_id) REFERENCES booking (id),
    CONSTRAINT fk_bsh_user FOREIGN KEY (changed_by) REFERENCES users (id)
);
