CREATE TABLE subscription_plan
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    price_monthly DECIMAL,
    booking_limit INTEGER                                  NOT NULL,
    sms_enabled   BOOLEAN                                  NOT NULL,
    multi_branch  BOOLEAN                                  NOT NULL,
    CONSTRAINT pk_subscription_plan PRIMARY KEY (id)
);

CREATE TABLE tenant_subscription
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    status     VARCHAR(255),
    tenant_id  INTEGER,
    plan_id    INTEGER,
    CONSTRAINT pk_tenant_subscription PRIMARY KEY (id),
    CONSTRAINT fk_tenant_subscription_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_tenant_subscription_plan FOREIGN KEY (plan_id) REFERENCES subscription_plan (id)
);

CREATE TABLE payment
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount          DECIMAL,
    currency        VARCHAR(255),
    provider_tx_id  VARCHAR(255),
    status          VARCHAR(255),
    paid_at         TIMESTAMP WITHOUT TIME ZONE,
    tenant_id       INTEGER,
    subscription_id INTEGER,
    CONSTRAINT pk_payment PRIMARY KEY (id),
    CONSTRAINT fk_payment_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_payment_subscription FOREIGN KEY (subscription_id) REFERENCES tenant_subscription (id)
);