CREATE TABLE notification
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    channel    VARCHAR(255),
    recipient  VARCHAR(255),
    type       VARCHAR(255),
    is_sent    BOOLEAN                                  NOT NULL,
    sent_at    TIMESTAMP WITHOUT TIME ZONE,
    booking_id INTEGER,
    CONSTRAINT pk_notification PRIMARY KEY (id),
    CONSTRAINT fk_notification_booking FOREIGN KEY (booking_id) REFERENCES booking (id)
);

CREATE TABLE review
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating     INTEGER                                  NOT NULL,
    comment    VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    tenant_id  INTEGER,
    client_id  INTEGER,
    staff_id   INTEGER,
    booking_id INTEGER,
    CONSTRAINT pk_review PRIMARY KEY (id),
    CONSTRAINT fk_review_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_review_client FOREIGN KEY (client_id) REFERENCES users (id),
    CONSTRAINT fk_review_staff FOREIGN KEY (staff_id) REFERENCES staff (id),
    CONSTRAINT fk_review_booking FOREIGN KEY (booking_id) REFERENCES booking (id)
);